'use strict';

module.exports = {
  HEX: 'HEX',
  NUMBER: 'NUMBER',
  DECIMAL: 'DECIMAL',
  INTEGER: 'INTEGER',
  STRING: 'STRING',
  LITERAL: 'LITERAL',
  MS: 'MS',
  MB: 'MB',
  KB: 'KB',
  ARROW: 'ARROW',
  ISOLATE: 'ISOLATE',
  SCAVENGE: 'scavenge',
  MARK_SWEEP: 'mark_sweep',
  MEMORY_ALLOCATOR: 'memory_allocator',
  NEW_SPACE: 'new_space',
  OLD_POINTERS: 'old_pointers',
  OLD_DATA_SPACE: 'old_data_space',
  CODE_SPACE: 'code_space',
  MAP_SPACE: 'map_space',
  CELL_SPACE: 'cell_space',
  PROPERTY_CELL_SPACE: 'property_cell_space',
  LARGE_OBJECT_SPACE: 'large_object_space',
  ALL_SPACES: 'all_spaces',
  OLD_SPACE: 'old_space',
  TOTAL_TIME: 'total_time_spent_in_gc',
  EXTERNAL_MEMORY: 'external_memory_reported',
  USED: 'used',
  AVAILABLE: 'available',
  COMMITED: 'committed',
  PROMOTED: 'promoted',
  START: 'start',
  PROMOTION: 'promotion'
};
